# Generated by Django 4.0.5 on 2023-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipeapp', '0002_remove_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(default='', upload_to='media_file'),
            preserve_default=False,
        ),
    ]
