# Generated by Django 4.1 on 2023-10-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipeapp", "0003_recipe_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe", old_name="images", new_name="image",
        ),
    ]
